<header data-layout class="col-12">
    <div class="row">
    <div class="float-left col-2">
        <h4 class="logo-wp"><a class="logo-text" href="">Zuul</a></h4>
    </div>
    
    <div class="col-4" id="global-search">
        <div class="row">
          <div class="col-12 search-holder">
            <input class="form-input" type="text" value="<?=date('d/M/Y')?>" id="example-text-input">
          </div>
        </div>
    </div>
    
    <div class="float-right col">
        <nav>
            <ul>
                <li><a href="">Utilizatori</a></li>
                <li><a href="">Module</a></li>
                <li><a href="">Alerte</a></li>
                <li><a href="">Contul meu</a></li>
            </ul>
        </nav>    
    </div>
    </div>
</header>