<div>
    <br /><br /><br />
    <section class="col-xs front-widget-row">
        <div class="front-widget-item">
             <div><i class="fa fa-user-circle-o" aria-hidden="true"></i></div>
            <h6>Utilizatori</h6>
        </div>
        
        <div class="front-widget-item">
            <div><i class="fa fa-id-card" aria-hidden="true"></i></div>
            <h6>Dosar nou</h6>
        </div>
        
        <div class="front-widget-item">
            <div><i class="fa fa-list-alt" aria-hidden="true"></i></div>
            <h6><a href="">Lista dosare</a></h6>
        </div>
        
        <div class="front-widget-item">
            <div><i class="fa fa-stack-exchange" aria-hidden="true"></i></div>
            <h6><a href="">Templates</a></h6>
        </div>
        
        <div class="front-widget-item">
            <div><i class="fa fa-file-text-o" aria-hidden="true"></i></div>
            <h6><a href="">Template nou</a></h6>
        </div>
    </section>
    
    <section class="col-xs front-widget-row">
        <div class="front-widget-item">
            <div><i class="fa fa-bell" aria-hidden="true"></i></div>
            <h6>Notificari</h6>
        </div>
    </section>           
    
    <section class="col-xs front-widget-row">
        <div class="front-widget-item">
            <div><i class="fa fa-desktop" aria-hidden="true"></i></div>
            <h6>Contul meu</h6>
        </div>
    </section>
    
    <section class="col-xs front-widget-row">
        
    </section>
</div>