<div>
    <header data-type="title" class='row'>
        <div class="col">
            <h4>Adauga un nou template</h4>
        
            <button class="form-btn" data-submit="TemplateForm">
                <?php if($action === 'NEW' ) : ?> Adauga <?php endif;?>
                <?php if($action === 'EDIT' ) : ?> Salvează <?php endif;?>
            </button>
        </div>
    </header>
    
    <content>
       
            <form method="POST" class="row" id="TemplateForm">
                <div class="ck-editor-container col-8 pl20 pr20">
                    <div id="form-elements">
                        <?php foreach($form->getFields() as $field) : ?>
                        <button class="mb5 form-btn-default" value="<?=$field->getFieldKey()?>"
                                data-form-element
                                ><?=$field->getFieldName()?></button>
                        <?php endforeach; ?>
                    </div>
                    <textarea name="template-editor" id="template-editor" rows="40" cols="80">
                        <?php echo $template->getContent()?>
                    </textarea>    
                </div>
                
                <div class="col-4 mt20">
                    
                    <div class="form-group row">
                      <label for="example-text-input" class="col-3">Denumire</label>
                      <div class="col">
                          <input class="form-input" type="text" name="template_name" placeholder="Denumire act" value="<?=$template->getTemplateName()?>" id="">
                      </div>
                    </div>
                    
                    <div class="form-group row">
                      <label for="example-search-input" class="col-3">Autor</label>
                      <div class="col">
                        <input class="form-input" readonly type="text" name="template_owner" value="Cornelius M." id="">
                      </div>
                    </div>
                    
                    <div class="form-group row">
                      <label for="example-search-input" class="col-3">Creat la</label>
                      <div class="col">
                        <input class="form-input" type="text" readonly name="template_created_at" value="<?= date('d, M Y, H:i')?>"     id="">
                      </div>
                    </div>
                    
                    <div class="form-group row">
                        <?php foreach($form->getFields() as $field) : ?>
                            <pre><?php var_dump($field->getFieldKey());?></pre>
                        <?php endforeach; ?>
                        
                        
                    </div>
                    
                </div>
                
            </form>
        </div>
        
    </content>
    
</div>

<?php
    $this->inlineScript()->appendFile($this->basePath('assets/node_modules/ckeditor/ckeditor.js'));
    $this->inlineScript()->appendFile($this->basePath('assets/app/template.js'));
?>